pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: Build failed.
    manager: IndependentPipelineManager
    precedence: low
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment: (?i)recheck
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline
    manager: DependentPipelineManager
    precedence: normal
    require:
      open: True
      current-patchset: True
      approval:
        - verified: [1, 2]
          username: zuul
        - code-review: 2
    trigger:
      gerrit:
        - event: comment-added
          approval:
            - code-review: 2
        - event: comment-added
          approval:
            - verified: 1
          username: zuul
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2


projects:
  - name: testproject
    check:
      - testproject-unit-tests
    gate:
      - testproject-unit-tests
