- name: Ensure puppet-apply is executed
  hosts: "{{ node }}"
  sudo: yes

  tasks:
  - name: ensure puppet-apply is executed
    command: bash -lc "puppet apply --debug /vagrant/puppet/init.pp --modulepath=/etc/puppet/modules/ --hiera_config=/vagrant/puppet/hiera/hiera.yaml --verbose"
    register: command_result
    failed_when: "command_result.rc != 0"
